name: builds-release-candidate

on:
  push:
    branches:
      - 'hotfix/**'
      - 'release/**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs: